### ISSUE TITLE
Timer label is not visible when UICircularTimerRing is animating

### ISSUE THREAD

**Issue by tomerciucran** [luispadron/UICircularProgressRing#171]
## Bug Report

:warning: **Your issue will be closed if these are not filled out**. :warning:

#### Version

6.0.0

#### Overview of what you tried to do

Implement a UICircularTimerRing with a custom formatter.

#### What is the expected outcome?

the circle ring being animated and the timer label displaying each second as expected.

#### What is the actual outcome?

the label in the middle of the circle is only visible before the animation starts and after it finishes.
Could be related to the gradient changes on the last update because it was working fine on 5.1.0. Same result with or without a custom value formatter.

#### Post sample code or example here

*If sample code can't be provided because it's too long, please provide a small example project,
where I can test, if you cannot provide either. There is not much I can do.*

```swift
class ExerciseBreakCircularRingValueFormatter: UICircularRingValueFormatter {
    let totalDuration: CGFloat
    
    init(totalDuration: CGFloat) {
        self.totalDuration = totalDuration
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func string(for value: Any) -> String? {
        guard let value = value as? CGFloat else { return nil }
        let interval = totalDuration - value
        let minutes = Int(interval) / 60 % 60
        let seconds = Int(interval) % 60
        return String(format: "%02i:%02i", minutes, seconds)
    }
}

class ExerciseBreakViewController: UIViewController, Pausable {
   @IBOutlet weak var progressView: UICircularTimerRing! {
        didSet {
            progressView.font = Fonts.getFont(type: .headlineBold)
            progressView.valueFormatter = ExerciseBreakCircularRingValueFormatter(totalDuration: CGFloat(viewModel.duration.value))
        }
    }

   override func viewDidAppear(_ animated: Bool) {
      self.progressView.startTimer(to: duration) { [weak self] state in
                guard let `self` = self else { return }
                switch state {
                case .finished:
                    self.delegate?.exerciseItemDidEnd(exercise: self.viewModel)
                default: break
                }
            }
   }
}
```
#### Have you tried fixing this yourself?

This project is open source, and I'm a student with very minimal amount of time.
Please give an attempt at fixing the issue first before creating a bug report.
This saves everyone time and benefits anyone who uses the library.
Pull requests are welcome!

**Comment by oztiryakimeric** [comment]
Same here. I don't even use value formatter.

**Comment by luispadron** [comment]
weird, i’ll take a look this weekend

**Comment by luispadron** [comment]
Fixed in [v6.0.1](https://github.com/luispadron/UICircularProgressRing/releases/tag/v6.0.1), thanks for reporting this!

**Comment by hohteri** [comment]
At least carthage v6.0.1 still has this bug, doesn't exist on master though.

**Comment by luispadron** [comment]
must’ve uploaded the wrong built framework then, i’ll upload the correct one when i get a chance

**Comment by luispadron** [comment]
@hohteri could you verify this is fixed for Carthage now? I built a new framework.zip and am curious if that was the issue.

**Comment by hohteri** [comment]
Unfortunately the issue still remains. It also still downloads v6.0.1 in case that piece of information is of any use. Master branch works as expected.

**Comment by luispadron** [comment]
it’s still v6.0.1 i just re uploaded the binary, maybe carthage is caching it?

**Comment by hohteri** [comment]
I used it on laptop which I never had downloaded  the library before. I’ll retest on my  desktop

**Comment by luispadron** [comment]
@hohteri should be fixed now, just tested it. You may have to do `rm -rf Carthage` and `Carthage update --platform iOS` again

**Comment by hohteri** [comment]
Yes, now it works. Thank you!
